# Generated by Django 3.1.2 on 2021-06-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210610_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
